-- ═══════════════════════════════════════════════════════════════════════════════════
-- PROPOSED — NOT APPLIED. Design doc §1 (B1).
-- Teacher Education — ONE FLAT category (owner decision, 2026-10-03: "one flat category
-- under the admission pillar (slug teacher-education). No sub-category tree unless you
-- show me why it's needed now." Nothing needs a tree now, so this file deliberately does
-- NOT create children).
--
-- Categories already live in the DB (table `categories`, migrations/20260702150637:2-20);
-- adding this row is a DATA operation done through the existing /categories admin screen
-- (src/pages/categories/CategoriesPage.tsx), NOT code. The owner will add it themselves.
-- AI Fill must read `categories` (not the hard-coded prompt list at
-- src/lib/ai/autofill.ts:168) — that wiring is a later slice (S2), not S1.
--
-- pillar value: entrance-exam (public root /admission; per the DB CHECK on exams
-- pillar<->entity_type, migrations/20260926023410:13). A state counselling admission
-- (UP D.El.Ed) is entity_type='university-admission' + selection_model='merit-based' (§1 B2).
--
-- If a tree is ever justified later, children (d-el-ed, b-ed, m-ed, shiksha-shastri) can
-- be added via parent_id; exams.subcategory_id already exists. Deferred until needed.
-- ═══════════════════════════════════════════════════════════════════════════════════

-- Single flat row — SKETCH ONLY (the owner creates this via the /categories UI, so this
-- file is documentation of the intended row, NOT an applied migration):
-- INSERT INTO categories (slug, name, pillar, order_index, is_active)
-- VALUES ('teacher-education', 'Teacher Education', 'entrance-exam', <n>, true)
-- ON CONFLICT (slug) DO NOTHING;
