ALTER TABLE cms_categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE cms_authors ENABLE ROW LEVEL SECURITY;
ALTER TABLE cms_tags ENABLE ROW LEVEL SECURITY;
ALTER TABLE cms_media ENABLE ROW LEVEL SECURITY;
ALTER TABLE cms_media_variants ENABLE ROW LEVEL SECURITY;
ALTER TABLE cms_articles ENABLE ROW LEVEL SECURITY;
ALTER TABLE cms_article_tags ENABLE ROW LEVEL SECURITY;
ALTER TABLE cms_article_categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE cms_pages ENABLE ROW LEVEL SECURITY;
ALTER TABLE cms_editorials ENABLE ROW LEVEL SECURITY;
ALTER TABLE cms_editorial_articles ENABLE ROW LEVEL SECURITY;
ALTER TABLE cms_events ENABLE ROW LEVEL SECURITY;
ALTER TABLE cms_exams ENABLE ROW LEVEL SECURITY;
ALTER TABLE cms_holidays ENABLE ROW LEVEL SECURITY;
ALTER TABLE cms_institutions ENABLE ROW LEVEL SECURITY;
ALTER TABLE cms_places ENABLE ROW LEVEL SECURITY;
ALTER TABLE cms_restaurants ENABLE ROW LEVEL SECURITY;
ALTER TABLE cms_results ENABLE ROW LEVEL SECURITY;
ALTER TABLE cms_education_news ENABLE ROW LEVEL SECURITY;
ALTER TABLE cms_site_settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE cms_internal_links ENABLE ROW LEVEL SECURITY;
ALTER TABLE cms_microsite_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE cms_ads ENABLE ROW LEVEL SECURITY;
ALTER TABLE cms_ad_events ENABLE ROW LEVEL SECURITY;
ALTER TABLE cms_content_versions ENABLE ROW LEVEL SECURITY;
ALTER TABLE cms_audit_log ENABLE ROW LEVEL SECURITY;
ALTER TABLE cms_ai_usage ENABLE ROW LEVEL SECURITY;
ALTER TABLE cms_webhook_log ENABLE ROW LEVEL SECURITY;
ALTER TABLE cms_system_config ENABLE ROW LEVEL SECURITY;
ALTER TABLE cms_users ENABLE ROW LEVEL SECURITY;
ALTER TABLE cms_roles ENABLE ROW LEVEL SECURITY;
ALTER TABLE cms_permissions ENABLE ROW LEVEL SECURITY;
ALTER TABLE cms_ai_permissions ENABLE ROW LEVEL SECURITY;
ALTER TABLE cms_ai_config ENABLE ROW LEVEL SECURITY;

-- Service role full access on all tables
CREATE POLICY "service_all" ON cms_categories FOR ALL TO service_role USING (true);
CREATE POLICY "service_all" ON cms_authors FOR ALL TO service_role USING (true);
CREATE POLICY "service_all" ON cms_tags FOR ALL TO service_role USING (true);
CREATE POLICY "service_all" ON cms_media FOR ALL TO service_role USING (true);
CREATE POLICY "service_all" ON cms_media_variants FOR ALL TO service_role USING (true);
CREATE POLICY "service_all" ON cms_articles FOR ALL TO service_role USING (true);
CREATE POLICY "service_all" ON cms_article_tags FOR ALL TO service_role USING (true);
CREATE POLICY "service_all" ON cms_article_categories FOR ALL TO service_role USING (true);
CREATE POLICY "service_all" ON cms_pages FOR ALL TO service_role USING (true);
CREATE POLICY "service_all" ON cms_editorials FOR ALL TO service_role USING (true);
CREATE POLICY "service_all" ON cms_editorial_articles FOR ALL TO service_role USING (true);
CREATE POLICY "service_all" ON cms_events FOR ALL TO service_role USING (true);
CREATE POLICY "service_all" ON cms_exams FOR ALL TO service_role USING (true);
CREATE POLICY "service_all" ON cms_holidays FOR ALL TO service_role USING (true);
CREATE POLICY "service_all" ON cms_institutions FOR ALL TO service_role USING (true);
CREATE POLICY "service_all" ON cms_places FOR ALL TO service_role USING (true);
CREATE POLICY "service_all" ON cms_restaurants FOR ALL TO service_role USING (true);
CREATE POLICY "service_all" ON cms_results FOR ALL TO service_role USING (true);
CREATE POLICY "service_all" ON cms_education_news FOR ALL TO service_role USING (true);
CREATE POLICY "service_all" ON cms_site_settings FOR ALL TO service_role USING (true);
CREATE POLICY "service_all" ON cms_internal_links FOR ALL TO service_role USING (true);
CREATE POLICY "service_all" ON cms_microsite_items FOR ALL TO service_role USING (true);
CREATE POLICY "service_all" ON cms_ads FOR ALL TO service_role USING (true);
CREATE POLICY "service_all" ON cms_ad_events FOR ALL TO service_role USING (true);
CREATE POLICY "service_all" ON cms_content_versions FOR ALL TO service_role USING (true);
CREATE POLICY "service_all" ON cms_audit_log FOR ALL TO service_role USING (true);
CREATE POLICY "service_all" ON cms_ai_usage FOR ALL TO service_role USING (true);
CREATE POLICY "service_all" ON cms_webhook_log FOR ALL TO service_role USING (true);
CREATE POLICY "service_all" ON cms_system_config FOR ALL TO service_role USING (true);
CREATE POLICY "service_all" ON cms_users FOR ALL TO service_role USING (true);
CREATE POLICY "service_all" ON cms_roles FOR ALL TO service_role USING (true);
CREATE POLICY "service_all" ON cms_permissions FOR ALL TO service_role USING (true);
CREATE POLICY "service_all" ON cms_ai_permissions FOR ALL TO service_role USING (true);
CREATE POLICY "service_all" ON cms_ai_config FOR ALL TO service_role USING (true);

-- Anon read for published content
CREATE POLICY "anon_read" ON cms_articles FOR SELECT TO anon USING (status = 'published');
CREATE POLICY "anon_read" ON cms_editorials FOR SELECT TO anon USING (status = 'published');
CREATE POLICY "anon_read" ON cms_events FOR SELECT TO anon USING (status = 'published');
CREATE POLICY "anon_read" ON cms_exams FOR SELECT TO anon USING (status = 'published');
CREATE POLICY "anon_read" ON cms_institutions FOR SELECT TO anon USING (status = 'published');
CREATE POLICY "anon_read" ON cms_places FOR SELECT TO anon USING (status = 'published');
CREATE POLICY "anon_read" ON cms_restaurants FOR SELECT TO anon USING (status = 'published');
CREATE POLICY "anon_read" ON cms_results FOR SELECT TO anon USING (status = 'published');
CREATE POLICY "anon_read" ON cms_education_news FOR SELECT TO anon USING (status = 'published');
CREATE POLICY "anon_read" ON cms_categories FOR SELECT TO anon USING (true);
CREATE POLICY "anon_read" ON cms_authors FOR SELECT TO anon USING (true);
CREATE POLICY "anon_read" ON cms_tags FOR SELECT TO anon USING (true);
CREATE POLICY "anon_read" ON cms_media FOR SELECT TO anon USING (true);
CREATE POLICY "anon_read" ON cms_pages FOR SELECT TO anon USING (is_published = true);
CREATE POLICY "anon_read" ON cms_holidays FOR SELECT TO anon USING (true);
CREATE POLICY "anon_read" ON cms_internal_links FOR SELECT TO anon USING (enabled = true);
CREATE POLICY "anon_read" ON cms_microsite_items FOR SELECT TO anon USING (true);
CREATE POLICY "anon_read" ON cms_site_settings FOR SELECT TO anon USING (true);
CREATE POLICY "anon_read" ON cms_ads FOR SELECT TO anon USING (is_active = true);
CREATE POLICY "anon_insert" ON cms_ad_events FOR INSERT TO anon WITH CHECK (true);;
