CREATE TABLE IF NOT EXISTS cms_authors (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  slug TEXT NOT NULL UNIQUE,
  name TEXT NOT NULL,
  name_hindi TEXT,
  email TEXT UNIQUE,
  avatar_url TEXT,
  cover_image_url TEXT,
  bio TEXT,
  bio_hindi TEXT,
  designation TEXT,
  expertise TEXT,
  profession TEXT,
  other_roles TEXT,
  experience TEXT,
  website_url TEXT,
  linkedin_url TEXT,
  facebook_url TEXT,
  instagram_url TEXT,
  twitter_url TEXT,
  whatsapp_url TEXT,
  knows_about JSONB,
  social_links JSONB,
  role TEXT DEFAULT 'author' CHECK (role IN ('admin', 'editor', 'author', 'contributor')),
  is_active BOOLEAN DEFAULT true,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_cms_authors_slug ON cms_authors(slug);;
